services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - DATABASE_URI=mongodb://mongo:27017/api-one
            - API_CHAT_GPT_BASE_URL=http://api-chat-gpt:4000
        depends_on:
            - mongo
            - api-chat-gpt
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        command: npm start

    api-chat-gpt:
        build:
            context: ../api-chat-gpt
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        environment:
            - NODE_ENV=production
            - OPENAI_API_KEY=
            - OPENAI_API_ORGANIZATION=
        command: npm start

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
